name=ATD3.5-S3_HandySense_Arduino_Library
version=1.0.0
author=ArtronShop Co.,Ltd.
maintainer=Sonthaya.NT <sonthaya.nt@artronshop.co.th>
sentence=Arduino library of ATD3.5-S3 Farm1 shield using HandySense platform for agritech solutions
paragraph=Arduino library of ATD3.5-S3 Farm1 shield using HandySense platform for agritech solutions
category=Sensors
url=https://github.com/ArtronShop/ATD3.5-S3-HandySense-Arduino-Library
architectures=*
